base/urls.py
from django.urls import path
from .views import *

app_name = 'base'

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'), 
]

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', blogs, name='blogs'),
    path('<slug:blog_slug>/', blog_detail, name='blog_detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('services/', include('services.urls')),
    path('blogs/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path
from .views import *

app_name = 'service'

urlpatterns = [
    path('', services, name='services'),
    path('<slug:service_slug>/', service_detail, name='service_detail'),
]

base/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blogs')
    image = models.CharField(max_length=255, null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.slug or slugify(self.title) != self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'

services/models.py
from django.db import models
from django.utils.text import slugify

class Service(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    icon_class = models.CharField(max_length=100)
    is_featured = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug or slugify(self.title) != self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['title']
        verbose_name = 'Service'
        verbose_name_plural = 'Services'

base/views.py
from django.shortcuts import render
from services.models import Service
from django.contrib import messages
from blog.models import Blog
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.urls import reverse

def index(request):
    
    static_content = """
        
        <div class="inner">
            <h1>HyperSpace</h1>
            <p>Just another fine responsive site template designed by <a href="http://html5up.net">HTML5 UP</a><br />
            and released for free under the <a href="http://html5up.net/license">Creative Commons</a>.</p>
            <ul class="actions">
                <li><a href="#one" class="button scrolly">Learn more</a></li>
            </ul>
        </div>
    
    """
    
    featured_services = Service.objects.filter(is_featured=True)
    latest_blogs = Blog.objects.all()[:3]
    
    context = {
        'static_content' : static_content,
        'services' : featured_services,
        'latest_blogs' : latest_blogs
    }
    return render(request, 'base/index.html', context)


def contact(request):
    
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        
        subject = f"Hyperspace Contact From"
        message_body = f"Name: {name}\nEmail: {email}\nMessage: {message}"
        recipient_list = [settings.EMAIL_HOST_USER]
        
        try:
            send_mail(subject, message_body, email, recipient_list)
        except Exception:
            messages.error(request, 'An error occurred while sending the email. Please try again later.')
        else:
            messages.success(request, 'Your message has been sent successfully!')
    
    return HttpResponseRedirect(reverse('base:index') + '#three')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
from django.core.paginator import Paginator

def blogs(request):
    blogs = Blog.objects.all()
    paginator = Paginator(blogs, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'blogs': blogs,
        'page_obj': page_obj,
    }
    return render(request, 'blog/blogs.html', context)


def blog_detail(request, blog_slug):
    blog = get_object_or_404(Blog, slug=blog_slug)
    context = {
        'blog': blog
    }
    return render(request, 'blog/blog-details.html', context)

services/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Service

def services(request):
    services = Service.objects.all()
    
    context = {
        'services': services
    }
    
    return render(request, 'services/services.html', context)


def service_detail(request, service_slug):
    
    service = get_object_or_404(Service, slug=service_slug)
    
    context = {
        'service': service
    }
    
    return render(request, 'services/service-details.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
	
    {% include "partials/_header.html" %}

	<body class="is-preload">

        {% include "partials/_sidebar.html" %}

        <div id="wrapper">
            {% block content %}
            {% endblock %}
        </div>

        {% include "partials/_footer.html" %}

    </body>
</html>

templates/base/index.html
{% extends "base.html" %}
{% load static %}

{% block title %} Home Page {% endblock %}

{% block content %}

    <section id="intro" class="wrapper style1 fullscreen fade-up">
       {{ static_content|safe }}
    </section>

    <section id="one" class="wrapper style3 fade-up">
        <div class="inner">
            <h2>What we do</h2>
            <p>Phasellus convallis elit id ullamcorper pulvinar. Duis aliquam turpis mauris, eu ultricies erat malesuada quis. Aliquam dapibus, lacus eget hendrerit bibendum, urna est aliquam sem, sit amet imperdiet est velit quis lorem.</p>
            <div class="features">
                {% for service in services %}
                    <section>
                        <a href="{% url 'service:service_detail' service.slug %}">
                            <span class="{{ service.icon_class }}"></span>
                            <h3>{{ service.title }}</h3>
                            <p>{{ service.description|truncatechars:100 }}</p>
                        </a>
                    </section>
                {% endfor %}
            </div>
            <ul class="actions">
                <li><a href="{% url 'service:services' %}" class="button">Learn more</a></li>
            </ul>
        </div>
    </section>

    <section id="two" class="wrapper style2 spotlights">
        {% for blog in latest_blogs %}
            <section style="border-bottom: 1px solid #035063;">
                <a href="#" class="image">
                    {% if 'http' in blog.image %}
                        <img src="{{ blog.image }}" alt="" data-position="center center" />
                    {% else %}
                        <img src="{% static 'images/pic01.jpg' %}" alt="" data-position="center center" />
                    {% endif %}
                </a>
                <div class="content">
                    <div class="inner">
                        <h2>{{ blog.title }}</h2>
                        <p>{{ blog.content|truncatechars:100 }}</p>
                        <ul class="actions">
                            <li><a href="{% url 'blog:blog_detail' blog.slug %}" class="button">Learn more</a></li>
                        </ul>
                    </div>
                </div>
            </section>
        {% endfor %}
    </section>

    <section id="three" class="wrapper style1 fade-up">
        <div class="inner">
            <h2>Get in touch</h2>
            <p>Phasellus convallis elit id ullamcorper pulvinar. Duis aliquam turpis mauris, eu ultricies erat malesuada quis. Aliquam dapibus, lacus eget hendrerit bibendum, urna est aliquam sem, sit amet imperdiet est velit quis lorem.</p>

            {% if messages %}
                <div class="messages" style="margin: 20px 0; padding: 10px; border-radius: 5px;">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible" 
                            style="
                                margin-bottom: 10px; 
                                padding: 15px; 
                                border: 1px solid #ccc; 
                                border-radius: 5px; 
                                background-color: {% if message.tags == 'success' %}#d4edda{% elif message.tags == 'error' %}#f8d7da{% elif message.tags == 'info' %}#d1ecf1{% elif message.tags == 'warning' %}#fff3cd{% else %}#e2e3e5{% endif %}; 
                                color: {% if message.tags == 'success' %}#155724{% elif message.tags == 'error' %}#721c24{% elif message.tags == 'info' %}#0c5460{% elif message.tags == 'warning' %}#856404{% else %}#383d41{% endif %};
                            ">
                            {{ message }}
                            <span class="close" 
                                onclick="this.parentElement.style.display = 'none';" 
                                style="
                                    float: right; 
                                    font-weight: bold; 
                                    color: #000; 
                                    cursor: pointer; 
                                    margin-left: 10px;
                                ">&times;</span>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}


            <div class="split style1">
                <section>
                    <form method="post" action="{% url 'base:contact' %}">
                        {% csrf_token %}
                        <div class="fields">
                            <div class="field half">
                                <label for="name">Name</label>
                                <input type="text" name="name" id="name" />
                            </div>
                            <div class="field half">
                                <label for="email">Email</label>
                                <input type="email" name="email" id="email" />
                            </div>
                            <div class="field">
                                <label for="message">Message</label>
                                <textarea name="message" id="message" rows="5"></textarea>
                            </div>
                        </div>
                        <ul class="actions">
                            <li><button type="submit" class="button submit">Send Message</button></li>
                        </ul>
                    </form>
                </section>
                <section>
                    <ul class="contact">
                        <li>
                            <h3>Address</h3>
                            <span>12345 Somewhere Road #654<br />
                            Nashville, TN 00000-0000<br />
                            USA</span>
                        </li>
                        <li>
                            <h3>Email</h3>
                            <a href="#">user@untitled.tld</a>
                        </li>
                        <li>
                            <h3>Phone</h3>
                            <span>(000) 000-0000</span>
                        </li>
                        <li>
                            <h3>Social</h3>
                            <ul class="icons">
                                <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
                                <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
                                <li><a href="#" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
                                <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
                                <li><a href="#" class="icon brands fa-linkedin-in"><span class="label">LinkedIn</span></a></li>
                            </ul>
                        </li>
                    </ul>
                </section>
            </div>
        </div>
    </section>

{% endblock %}

templates/blog/blog-details.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <title>Generic - Hyperspace by HTML5 UP</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
</head>
<body class="is-preload">

    <header id="header">
        <a href="{% url 'base:index' %}" class="title">Hyperspace</a>
        <nav>
            <ul>
                <li><a href="{% url 'base:index' %}">Home</a></li>
                <li><a href="{% url 'blog:blogs' %}">Blogs</a></li>
                <li><a href="{% url 'blog:blog_detail' blog.slug %}" class="active">{{ blog.title }}</a></li>
            </ul>
        </nav>
    </header>

    <div id="wrapper">

            <section id="main" class="wrapper">
                <div class="inner">
                    <h1 class="major">{{ blog.title }}</h1>
                    <span class="image fit"><img src="{% static 'images/pic04.jpg' %}" alt="" /></span>
                    <p>{{ blog.content }}</p>
                </div>
            </section>

    </div>

    <footer id="footer" class="wrapper alt">
        <div class="inner">
            <ul class="menu">
                <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
            </ul>
        </div>
    </footer>

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'assets/js/browser.min.js' %}"></script>
    <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'assets/js/util.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

templates/blog/blogs.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
    <title>Generic - Hyperspace by HTML5 UP</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
</head>

<body class="is-preload">
        
    <header id="header">
        <a href="{% url 'base:index' %}" class="title">Hyperspace</a>
        <nav>
            <ul>
                <li><a href="{% url 'base:index' %}">Home</a></li>
                <li><a href="{% url 'blog:blogs' %}" class="active">Blogs</a></li>
            </ul>
        </nav>
    </header>

    <div id="wrapper">
        <section id="main" class="wrapper">
            <div class="inner">
                <div class="features">

                    {% for blog in page_obj %}
                        <a href="{% url 'blog:blog_detail' blog.slug %}">
                            <section style="width: 100%;">
                                <h3>{{ blog.title }} </h3>
                                <p>{{ blog.content|truncatechars:200 }}</p>
                            </section>
                        </a>
                    {% endfor %}

                </div>
            </div>
        </section>
    </div>

    <div class="pagination" style="display: flex; justify-content: center; align-items: center; margin: 20px 0;">
        <span class="step-links" style="font-family: Arial, sans-serif; color: white; background-color: #333; padding: 10px 20px; border-radius: 30px; display: flex; gap: 10px; align-items: center;">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="pagination-link" style="color: #fff; text-decoration: none; padding: 8px 15px; border-radius: 5px; transition: background-color 0.3s ease; display: flex; align-items: center;">
                    <span style="font-size: 16px;">&laquo;</span> 
                </a>
                <a href="?page={{ page_obj.previous_page_number }}" class="pagination-link" style="color: #fff; text-decoration: none; padding: 8px 15px; border-radius: 5px; transition: background-color 0.3s ease; display: flex; align-items: center;">
                    <span style="font-size: 16px;">&#8592;</span> 
                </a>
            {% endif %}
        
            <span class="current" style="color: #bbb; padding: 8px 15px; font-weight: bold; background-color: #444; border-radius: 5px;">
                {{ page_obj.number }}
            </span>
        
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="pagination-link" style="color: #fff; text-decoration: none; padding: 8px 15px; border-radius: 5px; transition: background-color 0.3s ease; display: flex; align-items: center;">
                    <span style="font-size: 16px;">&#8594;</span> 
                </a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="pagination-link" style="color: #fff; text-decoration: none; padding: 8px 15px; border-radius: 5px; transition: background-color 0.3s ease; display: flex; align-items: center;">
                    <span style="font-size: 16px;">&raquo;</span>
                </a>
            {% endif %}
        </span>
    </div>

    <footer id="footer" class="wrapper alt">
        <div class="inner">
            <ul class="menu">
                <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
            </ul>
        </div>
    </footer>

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'assets/js/browser.min.js' %}"></script>
    <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'assets/js/util.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

    <script>
        document.querySelectorAll('.pagination-link').forEach(function (link) {
            link.addEventListener('mouseover', function() {
                link.style.backgroundColor = '#444';
            });
            link.addEventListener('mouseout', function() {
                link.style.backgroundColor = '';
            });
        });
    </script>

</body>
</html>

templates/generic.html
<!DOCTYPE HTML>
<!--
	Hyperspace by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Generic - Hyperspace by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="assets/css/main.css" />
		<noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<a href="index.html" class="title">Hyperspace</a>
				<nav>
					<ul>
						<li><a href="index.html">Home</a></li>
						<li><a href="{% url 'service:services' %}" class="active">Generic</a></li>
						<li><a href="elements.html">Elements</a></li>
					</ul>
				</nav>
			</header>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<section id="main" class="wrapper">
						<div class="inner">
							<h1 class="major">A Generic Page</h1>
							<span class="image fit"><img src="images/pic04.jpg" alt="" /></span>
							<p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fergiat. Pellentesque in mi eu massa lacinia malesuada et a elit. Donec urna ex, lacinia in purus ac, pretium pulvinar mauris. Curabitur sapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique.</p>
							<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>
						</div>
					</section>

			</div>

		<!-- Footer -->
			<footer id="footer" class="wrapper alt">
				<div class="inner">
					<ul class="menu">
						<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

templates/partials/_footer.html
{% load static %}

<footer id="footer" class="wrapper style1-alt">
    <div class="inner">
        <ul class="menu">
            <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
    </div>
</footer>

<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'assets/js/browser.min.js' %}"></script>
<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
<script src="{% static 'assets/js/util.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>

templates/partials/_header.html
{% load static %}

<head>
    <title>Hyperspace by HTML5 UP</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
</head>

templates/partials/_sidebar.html
{% load static %}

<section id="sidebar" style="border-right: 1px solid white;">
    <div class="inner">
        <nav>
            <ul>
                <li><a href="#intro">Welcome</a></li>
                <li><a href="#one">Who we are</a></li>
                <li><a href="#two">What we do</a></li>
                <li><a href="#three">Get in touch</a></li>
            </ul>
        </nav>
    </div>
</section>

templates/services/service-details.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <title>Generic - Hyperspace by HTML5 UP</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
</head>
<body class="is-preload">

    <header id="header">
        <a href="{% url 'base:index' %}" class="title">Hyperspace</a>
        <nav>
            <ul>
                <li><a href="{% url 'base:index' %}">Home</a></li>
                <li><a href="{% url 'service:services' %}">Services</a></li>
                <li><a href="{% url 'service:service_detail' service.slug %}" class="active">{{ service.title }}</a></li>
            </ul>
        </nav>
    </header>

    <div id="wrapper">

            <section id="main" class="wrapper">
                <div class="inner">
                    <h1 class="major">{{ service.title }}</h1>
                    <span class="image fit"><img src="{% static 'images/pic04.jpg' %}" alt="" /></span>
                    <p>{{ service.description }}</p>
                </div>
            </section>

    </div>

    <footer id="footer" class="wrapper alt">
        <div class="inner">
            <ul class="menu">
                <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
            </ul>
        </div>
    </footer>

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'assets/js/browser.min.js' %}"></script>
    <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'assets/js/util.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

templates/services/services.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
    <title>Generic - Hyperspace by HTML5 UP</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
</head>

<body class="is-preload">
        
    <header id="header">
        <a href="{% url 'base:index' %}" class="title">Hyperspace</a>
        <nav>
            <ul>
                <li><a href="{% url 'base:index' %}">Home</a></li>
                <li><a href="{% url 'service:services' %}" class="active">Services</a></li>
            </ul>
        </nav>
    </header>

    <div id="wrapper">

            <section id="main" class="wrapper">
                <div class="inner">
                    <div class="features">

                        {% for service in services %}
                            <a href="{% url 'service:service_detail' service.slug %}">
                                <section style="width: 100%;">
                                    <span class="{{ service.icon_class }} "></span>
                                    <h3>{{ service.title }} </h3>
                                    <p>{{ service.description|truncatechars:300 }}</p>
                                </section>
                            </a>
                        {% endfor %}

                    </div>
                </div>
            </section>

    </div>

    <footer id="footer" class="wrapper alt">
        <div class="inner">
            <ul class="menu">
                <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
            </ul>
        </div>
    </footer>

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'assets/js/browser.min.js' %}"></script>
    <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'assets/js/util.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>